environment:
  CONAN_RUN_TESTS: True
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build_script:
  - cmake . -DGETOPT_TESTING=1 -DCMAKE_INSTALL_PREFIX=prefix
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
  - ctest . -C Release --output-on-failure
